# Generated by Django 4.1.7 on 2023-02-22 17:09

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('imobiliariaSA', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Fotos',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('foto', models.ImageField(blank=True, help_text='Escolha uma foto', upload_to='media/fotos/%Y/%m/%d', verbose_name='Foto')),
                ('descricao', models.TextField(help_text='Descrição', verbose_name='Descrição')),
                ('imovel', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='imobiliariaSA.imovel')),
            ],
            options={
                'verbose_name_plural': 'Fotos dos imóveis',
                'db_table': 'tab_fotosImoveis',
                'managed': True,
            },
        ),
    ]
